version: '3.3'

services:
    db:
      image: postgres
      environment: 
        POSTGRES_PASSWORD: password1
        POSTGRES_USER: postgres
        POSTGRES_DB: disthw_db
    server:
      build: .
      ports:
        - "8080:8080"
      depends_on:
        - db