version: '3.3'

services:
    db:
      image: postgres
    disthw:
      build: .
      command: python manage.py runserver 0.0.0.0:8080
      volumes:
        - .:/app
      ports:
        - "8080:8080"
      depends_on:
        - db