version: '3.3'

services:
    db:
      image: postgres
      environment: 
        POSTGRES_PASSWORD: password1
        POSTGRES_USER: postgres
        POSTGRES_DB: estore_db
      networks:
        - net
    estore:
      build:
        context: ./
        dockerfile: ./estore/Dockerfile
      ports:
        - "8080:8080"
      command: ["./wait.sh", "db:5432", "--", "./run.sh"]
      environment:
        DJANGO_PG_USER: postgres
        DJANGO_PG_PASSWORD: password1
        DJANGO_PG_HOST: db
        DJANGO_PG_PORT: 5432
        DJANGO_SECRET_KEY: secret123
      depends_on:
        - db
      networks:
        - net

networks:
  net: