version: '3.3'

services:
    rabbitmq:
      image: 'bitnami/rabbitmq:latest'
      environment:
        RABBITMQ_USERNAME: disthw
        RABBITMQ_PASSWORD: password1
        RABBITMQ_VHOST: disthw_host
      networks:
          - net 

    db:
      image: postgres
      volumes:
        - ./tools/create_multiple_pg_db.sh:/docker-entrypoint-initdb.d/create_multiple_pg_db.sh
      environment: 
        POSTGRES_PASSWORD: password1
        POSTGRES_USER: postgres
        POSTGRES_MULTIPLE_DATABASES: auth_db,estore_db
      networks:
        - net

    auth:
      build:
        context: ./
        dockerfile: ./auth/Dockerfile
      ports:
        - "8080:8080"
      command: ["./wait_postgres.sh", "./run.sh"]
      environment:
        DJANGO_DEBUG: 1
        DJANGO_PG_USER: postgres
        DJANGO_PG_PASSWORD: password1
        DJANGO_PG_HOST: db
        DJANGO_PG_PORT: 5432
        DJANGO_SECRET_KEY: secret123
        PROXY_HOST: estore
        PROXY_PORT: 8080
        WAIT_PG_DB: auth_db
        NOTIFICATION_HOST: notification
        NOTIFICATION_PORT: 8080
      depends_on:
        - db
      networks:
        - net
        
    estore:
      build:
        context: ./
        dockerfile: ./estore/Dockerfile
      ports:
        - "8081:8080"
      command: ["./wait_postgres.sh", "./run.sh"]
      environment:
        DJANGO_DEBUG: 1
        DJANGO_PG_USER: postgres
        DJANGO_PG_PASSWORD: password1
        DJANGO_PG_HOST: db
        DJANGO_PG_PORT: 5432
        DJANGO_SECRET_KEY: secret123
        INTERNAL_SERVICES_ALLOWED_HOSTS: auth
        WAIT_PG_DB: estore_db
      depends_on:
        - db
      networks:
        - net

    notification:
      build:
        context: ./
        dockerfile: ./notification/Dockerfile
      ports:
        - "8082:8080"
      command: ["./wait.sh", "rabbitmq:5672", "--", "./run_notification.sh"]
      environment:
        DJANGO_DEBUG: 1
        DJANGO_SECRET_KEY: secret123
        INTERNAL_SERVICES_ALLOWED_HOSTS: auth
        DJANGO_BROKER_USER: disthw
        DJANGO_BROKER_PASSWORD: password1
        DJANGO_BROKER_HOST: rabbitmq
        DJANGO_BROKER_PORT: 5672
        DJANGO_BROKER_VHOST: disthw_host
      depends_on:
        - rabbitmq
      networks:
        - net

networks:
  net: