# Generated by Django 3.0.3 on 2020-02-23 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='item',
            name='code',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
